//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace ExemploCriptografiaLoteEFinanceira.Schema
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.eFinanceira.gov.br/schemas/envioLoteCriptografado/v1_2_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.eFinanceira.gov.br/schemas/envioLoteCriptografado/v1_2_0", IsNullable=false)]
    public partial class eFinanceira {
        
        private eFinanceiraLoteCriptografado loteCriptografadoField;
        
        /// <remarks/>
        public eFinanceiraLoteCriptografado loteCriptografado {
            get {
                return this.loteCriptografadoField;
            }
            set {
                this.loteCriptografadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.eFinanceira.gov.br/schemas/envioLoteCriptografado/v1_2_0")]
    public partial class eFinanceiraLoteCriptografado {
        
        private string idField;
        
        private string idCertificadoField;
        
        private string chaveField;
        
        private string loteField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string idCertificado {
            get {
                return this.idCertificadoField;
            }
            set {
                this.idCertificadoField = value;
            }
        }
        
        /// <remarks/>
        public string chave {
            get {
                return this.chaveField;
            }
            set {
                this.chaveField = value;
            }
        }
        
        /// <remarks/>
        public string lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
            }
        }
    }
}
